IgorTest19/car_auction

- car_auction_service/templates/base.html
- car_auction_service/templates/navbar.html
Moved "log in" and "log out" functionalities from the base.html template to the navbar template
> moves loggin functionality to navbar

- car_auction_service/templates/base.html
Added new bootstrap head link and django static failes.
> bootstrap changes

- car_auction_service/users/forms.py
Creating file forms.py and implementing user registration form
> adding user registration form

- car_auction_service/templates/base.html
- car_auction_service/templates/navbar.html
Making changes into tailwind css instead of bootstrap.
> implementing tailwind css

- car_auction_service/cars/models.py
Added metadata class (Meta) to Car class model.
> metadata changes

- car_auction_service/cars/models.py
Changes in Meta class of Cars class model.
> verbose name changes

- car_auction_service/cars/forms.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/cars_list.html
Changes in dynamic car searching form.
> cars searching form

- car_auction_service/cars/filters.py
- car_auction_service/templates/cars/car_add.html
- car_auction_service/templates/cars/car_filter_form.html
Changed Car searching form to filter.
> Changed car searching

- car_auction_service/cars/forms.py
- car_auction_service/cars/models.py
- car_auction_service/cars/urls.py
- car_auction_service/cars/views.py
- car_auction_service/templates/navbar.html
Implementing needed changes for car adding including:
- changes in car adding form in forms.py
- adding user field to car model
- adding url in urls.py for new template car_add.html
- adding function car_add for adding a car in views.py
- modifications in navbar template navbar.html including link to car adding template.
> car adding changes

- car_auction_service/cars/models.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/user_dashboard.html
- car_auction_service/templates/navbar.html
- Created user dashboard template dashboard.html.
- Added car adding form to mentioned template.
- Added new field owner to car model.
- Other minor code changes related to this new functionallity.
> Creating user dashboard with functionalities

- car_auction_service/car_auction_service/settings.py
- car_auction_service/car_auction_service/urls.py
- car_auction_service/cars/models.py
- car_auction_service/templates/cars/car_add.html
- implementing changes in settings.py for media files
- adding changes for urls for django serwer being able to host photos on development stage, not production stage.
- modifing car model for photo fileld
> changes for car photos

- car_auction_service/cars/forms.py
- Enabling logged user to add photo in during adding car for an auction portal.
> adding photo to creating form

- car_auction_service/cars/views.py
- Adding login_required decorator for limiting acces for not logged users to user dashboard view
> User's restrictions

- car_auction_service/car_auction_service/settings.py
Modified settings.py
- adding variable  for pointing to folders with static files
- adding variable for pointing to urls for content generated/added by user. (images)
> added meddia settings

- car_auction_service/templates/cars/user_dashboard.html
Added displaying of specified car's id in html template
> Displaying car id

- car_auction_service/cars/models.py
- changed directory containing image files added by the user
- added model's ( Car class) function for returning image url or None in the case of not having the image
> model's image modifications

- car_auction_service/templates/cars/car_detail.html
- changed default width of the photo in the car_detail template.
> changeg default photo size

- car_auction_service/car_auction_service/settings.py
- car_auction_service/car_auction_service/urls.py
- adding django debug toolbar functionality for web browser real time debugging
> adding django debug toolbar

- car_auction_service/cars/models.py
- Adding valid boolean field into Car model for time validation. Each car gonna have specified time being able to see, depending on the additional payment.
> Adding valid field

- car_auction_service/templates/cars/car_detail.html
- car_auction_service/templates/cars/user_dashboard.html
- Added published date to the car detail template.
- Created condition which checks if listed car is user dashboard are exactly owner's cars. (dashboard template)
> dashboard owner only cars list

- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_detail.html
- car_auction_service/templates/cars/cars_list.html
- car_auction_service/templates/cars/user_dashboard.html
- cleaning car detail template by removing redundant code
- created another template for cars listing to remove repeated code and create template more useful. Removed cars listing code from user dashboard and landing page to add only inclusion of cars listing template to each of them (less code in both templates).
- removed redundant code in views.py
> Cars listing

- car_auction_service/cars/urls.py
- car_auction_service/templates/cars/car_detail.html
- adding car delete button to the car detail template
- adding car delete function in views.py
- adding route in cars/ursl.py to deleting cars functionallity
> car delete functionallity

- car_auction_service/cars/admin.py
- adding car id column display for image model in admin panel
- renaming columns for better readability
> adding changes in admin panel

- car_auction_service/cars/forms.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_add.html
- car_auction_service/templates/cars/car_detail.html
- added new fields for authenticated users: if car auction was updated and if car auction is still valid
> Multiple photos

- car_auction_service/templates/users/register.html
- adding user registration template
> user register init and template

- car_auction_service/cars/forms.py
- car_auction_service/templates/users/register.html
- Extending user regitration form
> User register

- car_auction_service/cars/views.py
- added function for user registratino in views.py
> user register functionality in views

- .gitignore
- .idea/misc.xml
- car_auction_service/car_auction_service/settings.py
- car_auction_service/car_auction_service/urls.py
- car_auction_service/cars/forms.py
- car_auction_service/cars/views.py
- car_auction_service/templates/users/register.html
- car_auction_service/users/forms.py
- car_auction_service/users/urls.py
- car_auction_service/users/views.py
Reverts IgorTest19/car_auction#52
> Revert "User register"

- car_auction_service/cars/filters.py
- car_auction_service/templates/cars/car_filter_form.html
- changed displaying form fileds in tamplets to modify them
- modifications in cars filtering to display suggested value (placeholder), different for each field.
> changes in cars filtering

- car_auction_service/cars/models.py
- changed default fields values for car brand and car model in Car class model
> changed default fields values

- car_auction_service/cars/admin.py
- car_auction_service/cars/forms.py
- car_auction_service/cars/models.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_add.html
- car_auction_service/templates/cars/car_detail.html
- car_auction_service/templates/cars/cars_list.html
- removing photo field in Car class model
- modifying forms for adding multiple photos
- modifying admin panel for adding multiple photos functionallity
- modification in views for adding car with multiple photos and displaying photos
- modifications in templates for this functionallity
> Adding multiple photos

- car_auction_service/cars/models.py
- car_auction_service/templates/cars/car_detail.html
- car_auction_service/templates/cars/cars_list.html
- changes the way of displaying multiple photos in car detail template by only car model, not using CarImage model.
- displaying single (first or main) photo in car list template.
> photo displaying modifications

- car_auction_service/cars/models.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_detail.html
- changed order of displayed car's photos
- changed to first photo of car's displayed photos list to be the first one from the list
> changed they way of photos displaying

- car_auction_service/maps/admin.py
- car_auction_service/maps/apps.py
- car_auction_service/maps/models.py
- car_auction_service/maps/tests.py
- car_auction_service/maps/views.py
- Created django maps application for car auction service additional maps functionallity
> created django maps application

- car_auction_service/cars/models.py
Adding missing docstrings to methods in the Car model and CarImage model in models.py
> adding docstrings to methods in models

- car_auction_service/cars/models.py
Added field users_observing in Car class model to make able multiple users to add specified car to observed (liked cars)
> added car observers filed

- car_auction_service/cars/urls.py
- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_detail.html
- in views.py added function to add a car to observed
- in template of car detail added button to add car to observed
- in urls.py added car observing route
> adding car to observed

- car_auction_service/cars/models.py
- modified relation type and values in "users_observing" field in Car model
- added function which returns string representation of observers
> changes in car model

- car_auction_service/users/__init__.py
- car_auction_service/users/apps.py
- car_auction_service/users/models.py
- car_auction_service/users/signals.py
- created signals file in users app and moved already signal function from users/models
- definited default app in __init__ for signals
- added ready function for UserConfig class in users/apps
> modifying signals for user profile

- car_auction_service/cars/views.py
- car_auction_service/templates/cars/user_dashboard.html
- car_auction_service/users/models.py
- car_auction_service/users/signals.py
- modified car_observe function to add observed cars to user instead of adding observing user to car
- modified dashboard template to show cars observed by user
- modified singals to fix user profile object
- modified user profile model by adding function for displaying all observed cars
> car observing functionallity

- car_auction_service/cars/views.py
- adding decorator/wrapper making adding cars to observed only for logged in users
> adding login restrictions to observing cars

- car_auction_service/cars/views.py
- adding paramters to login_required wrapper for redirection of not logged in users
> adding redirection for not logged users

- car_auction_service/templates/users/user_password_change.html
- car_auction_service/users/forms.py
- car_auction_service/users/views.py
- creating template for changing password
- creating logic for changing password in users views.py
- creating passwrod change form in forms.py
- adding url for password change
> Users featuers

- car_auction_service/cars/views.py
- car_auction_service/templates/base.html
- addint messages feature by modifying base tempalte and cars/views.py to adding car functionallity
> Messages feature

- car_auction_service/templates/cars/user_dashboard.html
- added filter to user dashobard template to make possible filtering/searching cars added by user.
> adding filtering user's cars

- car_auction_service/car_auction_service/urls.py
- car_auction_service/maps/urls.py
- car_auction_service/maps/views.py
- car_auction_service/templates/maps/map_main.html
- fixed paths and names values
- displaying raw map in maps template
> Django maps

- car_auction_service/templates/users/register_done.html
- changed the placement of user login link. Moved to to the end of the sentence and removed as standalone field.
> Changing login link placement

- car_auction_service/cars/views.py
- After successfully adding car, form is being cleaned.
> Cleaning car add form after adding a car

- car_auction_service/templates/cars/user_dashboard.html
- car_auction_service/users/models.py
- Modified user_dashboard template to display observed cars phots with hyperlinks.
- added new observed cars method to UserProfile model.
> added photo list of observed cars

- car_auction_service/templates/cars/car_detail.html
- changed visibility of observers of viewed car to be avaiable only for car owner.
> changed field visibility

- car_auction_service/cars/admin.py
- car_auction_service/cars/apps.py
- car_auction_service/cars/filters.py
- car_auction_service/cars/forms.py
- adding docstrings to the car app.
> Docstrings

- car_auction_service/cars/views.py
- Added docstrings to car_detail function in cars/views
> car detail docstirngs

- car_auction_service/car_auction_service/settings.py
- car_auction_service/templates/base.html
- car_auction_service/templates/cars/car_filter_form.html
- installed packages: django-crispy-forms and crispy-bootstrap5
- added bootstrap 5 to base.html template
- added crispy forms setup in settings.py (adding to installed apps and crispy_template_tag variable)
- modified car filter template by adding crispy froms (added crispy tags to form's fields)
> Crispy forms

- car_auction_service/templates/cars/car_filter_form.html
- modification of car fitlering form fields with crispy forms usage
> changes fields location and dimensions

- car_auction_service/templates/users/user_password_change.html
- added crispy for for user password change in tempalte user_password_change.html
- modified the design of the submit buttong for password change form
> Added crispy form for user password change template

- car_auction_service/cars/views.py
- fixed template passing as argument from template path to app-namespace naming convention for cars app.
> fixed paths from template source to app source

- car_auction_service/cars/views.py
- fixed redirections to dashboard
> fixed paths

- car_auction_service/cars/views.py
- changed template for dashboard view in cars/views
- adding car to observed now doesn't redirect to main template but stays in car's template
> Fixed redirections and responses

- car_auction_service/cars/views.py
- car_auction_service/templates/cars/car_detail.html
- added functionality: removing car from observed
- modified function car_observe in cars/views
- button for adding/removing car from observes changes it's color and text depending on the state of the observed value
> Removing car from observed

- car_auction_service/templates/cars/cars_list.html
- mofidied template consisting of list of cars adding fields for more of car's data.
> Cars modifications

- car_auction_service/cars/views.py
Added new fileds of car model to the car adding form:
- price
- fuel type
- engine_capacity
> added new fields to car add form

- car_auction_service/templates/users/register.html
- added button for cleaning form of user register functionality
> Added reset template button

- car_auction_service/cars/views.py
- changed initial focused view of the maps from the always fixed coordinates, to the view focus based on the car's coordinates.
> changed maps view

- car_auction_service/templates/footer.html
- made footer fixed to the bootom of the template
- changed footer height to smaller
> footer modifications

- car_auction_service/templates/base.html
- added top and bottom margins to main tempate base.html
> changes top and bottom margins

- car_auction_service/templates/messages.html
- Added closing modal window with javascript code
- Removed redundant code (other buttons)
> added modal window closing button

- car_auction_service/cars/views.py
- Added creation of default image when there are no other car's images during car edition
- Deleting default image when user adds other images.
> default image feature

- car_auction_service/templates/cars/car_edit2.html
- Changed site design to make buttons being positioned in one line.
> Buttons positioning

- car_auction_service/cars/admin.py
- car_auction_service/cars/filters.py
- car_auction_service/cars/forms.py
- car_auction_service/cars/models.py
- car_auction_service/cars/views._backup3.py
- car_auction_service/cars/views.py
- car_auction_service/users/models.py
- Initial code refactorisation was done
- Due to complexity of the task, refactorisation was partially reverted
- Added car advertisment model to car/models.py
> Car Advertisement model

- car_auction_service/cars/forms.py
- changed form fields for new ones.
> model name fix and fields changes

- car_auction_service/cars/models.py
- Modified fuel type filed as choice filed. Added fuel type choices to choose by an user.
> modified fuel type field

- car_auction_service/car_auctions/views.py
refactoring cars to cars_auction in app car_auction (previously cars) in views.py
> refactoring cars to cars_auction

- car_auction_service/templates/car_auctions/car_detail.html
- Changed the name of the unused object car to the proper, actual name: car_auction in the template car_detail.html
> changed object name form car to car_auction

- car_auction_service/car_auctions/views.py
- car_auction_service/templates/car_auctions/car_detail.html
- added utils import in views.py file in car_auctions app
- added id field in car detail template
> cleaning up files

- car_auction_service/car_auctions/utils.py
- car_auction_service/car_auctions/views.py
Reformating code in utils.py and views.py of car auction app.
> restyling code
